[chore] Update makefile script

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -10,52 +10,15 @@ if [[ "$FIRST_LINE" =~ ^Merge ]]; then
     exit 0
 fi
 
-if [[ "$FIRST_LINE" =~ ^(\[ci\ skip\]\ ?)?\[release\]\ .+ ]]; then
-    if [ "$BRANCH" != "main" ]; then
-        echo "Invalid commit message"
-        echo "[release] commits are only allowed on the 'main' branch"
-        exit 1
-    fi
-
-    VERSION=$(echo "$FIRST_LINE" | sed -n 's/^\(\[ci skip\][[:space:]]*\)\?\[release\][[:space:]]*\([^[:space:]]*\).*/\2/Ip')
-
-    if [ -z "$VERSION" ] || ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-        echo "Invalid version in commit message: $FIRST_LINE"
-        echo "Expected format: [release] X.Y.Z"
-        exit 1
-    fi
-
-    APP_VERSION=$(jq -r .version < package.json)
-
-    if [[ "$APP_VERSION" != "$VERSION" ]]; then
-        echo "App version $APP_VERSION does not match $VERSION, specified in commit message"
-        exit 1
-    fi
-
-    echo "CHECK: Looking for TODOs"
-    if grep -R -nP --exclude-dir={build,.git} '//\s*TODO:' src src-tauri/src > /tmp/todos.txt; then
-        sed 's/^\([^:]*:[^:]*\):/  \1\n    /' /tmp/todos.txt
-        echo "❌ Pending TODOs found in code"
-        exit 1
-    fi
-
-    echo "CHECK: Source code quality"
-    cargo clippy --manifest-path ./src-tauri/Cargo.toml -- -D warnings
-
-
-    echo "TEST: Building for release"
-    make build 
+if [[ "$FIRST_LINE" =~ ^(\[ci\ skip\]\ ?)?\[($REQUIRED_PREFIXES)\]\ .+ ]]; then
+    exit 0
 else
-    if [[ "$FIRST_LINE" =~ ^(\[ci\ skip\]\ ?)?\[($REQUIRED_PREFIXES)\]\ .+ ]]; then
-        exit 0
-    else
-        echo "Invalid commit message"
-        echo "Rules:"
-        echo " - Optional [ci skip] at the beginning"
-        echo " - Mandatory prefix: [fix], [feature], [docs], [test], [chore], [improve], [version], [changelog], [refactor], [release]"
-        echo " - A space and a non-empty message after the mandatory prefix"
-        echo " - [release] is only allowed on the 'main' branch"
-        echo " - Commits starting with 'Merge' are valid"
-        exit 1
-    fi
+    echo "Invalid commit message"
+    echo "Rules:"
+    echo " - Optional [ci skip] at the beginning"
+    echo " - Mandatory prefix: [fix], [feature], [docs], [test], [chore], [improve], [version], [changelog], [refactor], [release]"
+    echo " - A space and a non-empty message after the mandatory prefix"
+    echo " - [release] is only allowed on the 'main' branch"
+    echo " - Commits starting with 'Merge' are valid"
+    exit 1
 fi
